#!/usr/bin/env python

import argparse, socket, time, json, select, struct, math, copy, logging

DEBUG = True
logging.basicConfig(filename='router.log', level=logging.DEBUG)
#DEBUG = False
#logging.basicConfig(filename='example.log', level=logging.CRITICAL)



parser = argparse.ArgumentParser(description='route packets')
parser.add_argument('networks', metavar='networks', type=str, nargs='+', help="networks")
args = parser.parse_args()

##########################################################################################

# Message Fields
TYPE = "type"
SRCE = "src"
DEST = "dst"
MESG = "msg"
TABL = "table"

# Message Types
DATA = "data"
DUMP = "dump"
UPDT = "update"
RVKE = "revoke"
NRTE = "no route"

# Update Message Fields
NTWK = "network"
NMSK = "netmask"
ORIG = "origin"
LPRF = "localpref"
APTH = "ASPath"
SORG = "selfOrigin"

# internal route info
CUST = "cust"
PEER = "peer"
PROV = "prov"


##########################################################################################

class Router:
	routes = None
	updates = None
	relations = None
	sockets = None
	fwd_table = None

	def __init__(self, networks):
		self.routes = {}
		self.updates = {}  # Save update annoucements as { src : annoucement_msg }
		self.relations = {}  # {"192.168.0.2" : "peer"}
		self.sockets = {}  # socket.socket() for "192.168.0.2"
		self.fwd_table = []  #

		for relationship in networks:
			# Ex: 192.168.0.2-peer
			network, relation = relationship.split("-")  # network = "192.168.0.2", relation = "peer"
			# if DEBUG:
			logging.debug("Starting socket for {} - {}".format(network, relation))
			self.sockets[network] = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
			self.sockets[network].setblocking(0)
			self.sockets[network].connect(network)

			self.relations[network] = relation

			logging.debug("\n")

		return

	def lookup_routes(self, daddr):
		""" Lookup all valid routes for an address """
		# !!! DADDR IS A FULL PACKET, NOT JUST ADDRESS !!!
		# Perform DFS for the router at IP address == daddr
		# Return list of lists representing possible paths
		outroutes = []

		# Simple count of valid paths by checking forwarding table.
		# For each entry in fwd_table, checks equality of subnets of fwd_table entry and dst
		for entry in self.fwd_table:
			if self.get_subnet(daddr["dst"], entry["netmask"]) == self.get_subnet(entry["network"], entry["netmask"]):
				outroutes.append(entry)

		return outroutes

	def get_shortest_as_path(self, routes):
		""" select the route with the shortest AS Path """
		# TODO
		outroutes = []

		curr_shortest_as = None
		for route in routes:
			if curr_shortest_as is None:
				curr_shortest_as = len(route["ASPath"])
			logging.info("Current Shortest AS set to {}".format(len(route["ASPath"])))
			if len(route["ASPath"]) <= curr_shortest_as:
				outroutes.append(route)
			logging.info("{} routes with shortest_path".format(len(outroutes)))
		logging.debug(outroutes)
		return outroutes

	def get_highest_preference(self, routes):
		""" select the route with the highest localpref """
		# TODO
		if len(routes) == 0:
			return

		outroutes = []
		curr_max_lp = None

		for route in routes:
			if curr_max_lp is None:
				curr_max_lp = route["localpref"]

			if route["localpref"] >= curr_max_lp:
				curr_max_lp = route["localpref"]
				outroutes.append(route)

		return outroutes

	def get_self_origin(self, routes):
		""" select self originating routes """
		outroutes = []

		if len(routes) <= 1:
			return routes

		if "True" not in [d["selfOrigin"].decode('utf-8') for d in routes]:
			return routes
		else:
			for route in routes:
				if route['selfOrigin'].decode('utf-8') == "True":
					logging.debug("Route added: {}".format(route))
					outroutes.append(route)

		return outroutes

	def get_origin_routes(self, routes):
		""" select origin routes: EGP > IGP > UNK """
		# TODO
		outroutes = []

		if len(routes) <= 1:
			return routes

		origin_ranks = {"IGP": 1,
						"EGP": 2,
						"UNK": 3}

		# curr_best_origin = origin_ranks[routes[0]["origin"]]
		curr_best_origin = None
		for route in routes:
			if curr_best_origin is None:
				curr_best_origin = origin_ranks[route["origin"]]

			if origin_ranks[route["origin"]] <= curr_best_origin:
				curr_best_origin = origin_ranks[route["origin"]]
				outroutes.append(route)

		return outroutes

	def filter_relationships(self, srcif, routes):
		""" Don't allow Peer->Peer, Peer->Prov, or Prov->Peer forwards """
		outroutes = []
		if self.relations[srcif] == CUST:
			logging.debug("{} SRCIF IS CUST\n".format(srcif))
			return routes
		elif self.relations[srcif] == PEER:
			logging.debug("{} SRCIF IS PEER\n".format(srcif))
			for route in routes:
				if self.relations[route["peer"]] == CUST:
					outroutes.append(route)
			
		else:
			logging.debug("SRCIF IS PROV")
			for route in routes:
				if self.relations[route["peer"]] != PEER:
					outroutes.append(route)
		
		return outroutes[0] if len(outroutes) == 1 else None

	def get_min_ip(self, routes):
		temp = {}

		for route in routes:
			temp[int("".join(route["peer"].split(".")))] = route

		return temp[min(list(temp.keys()))]["peer"]

	def send_no_route(self, srcif, packet):
		self.forward(srcif, {"src": srcif[:-1] + "1",
					  "dst": packet["src"],
					  "type": "no route",
					  "msg": {}})

	def get_route(self, srcif, daddr):
		"""	Select the best route for a given address	"""
		# TODO
		peer = None
		routes = self.lookup_routes(daddr)
		logging.debug(routes)
		if len(routes) == 0 or routes is None:
			packet_copy = copy.deepcopy(daddr)
			logging.warning("No Routes Found\n")

			# Forwards message back to sender
			logging.debug("Sending packet back {}\n".format(packet_copy))
			self.send_no_route(srcif, packet_copy)

			return

		elif len(routes) == 1:
			packet_copy = copy.deepcopy(daddr)
			logging.debug("1 route found, forwarding packet to {}".format(packet_copy["dst"]))
			# Forwards message using only available path
			if self.filter_relationships(srcif, routes) is not None:
				return self.forward(routes[0]["peer"], packet_copy)
			else:
				return self.send_no_route(srcif, packet_copy)

		# Rules go here
		else:
			logging.debug("{} routes found, finding best route".format(len(routes)))
			# 1. Highest Preference
			routes = self.get_highest_preference(routes)
			logging.debug("Route list after get_highest_preference: {}".format(routes))
			# 2. Self Origin
			routes = self.get_self_origin(routes)
			logging.debug("Route list after get_self_origin: {}".format(routes))
			# 3. Shortest ASPath
			routes = self.get_shortest_as_path(routes)
			logging.debug("Route list after get_shortest_as_path: {}".format(routes))
			# 4. EGP > IGP > UNK
			routes = self.get_origin_routes(routes)
			logging.debug("Route list after get_origin_routes: {}".format(routes))
			# 5. Lowest IP Address
			# TODO assign peer to return of filter_relationships 
			# Once it is writter
			#peer = self.get_min_ip(routes)
			routes = self.get_min_ip(routes)
			# Final check: enforce peering relationships
			peer = self.filter_relationships(srcif, routes)

		return self.forward(peer, daddr) if peer is not None  else self.send_no_route(srcif, daddr)
		

	def forward(self, srcif, packet):
		"""	Forward a data packet	"""
		logging.warning("Forwarding {} to {}".format(packet["type"], packet["dst"]))

		self.sockets[srcif].sendto(json.dumps(packet), packet["dst"])
		logging.warning(self.fwd_table)


		return

	def coalesce(self):
		"""	coalesce any routes that are right next to each other	"""
		# TODO (this is the most difficult task, save until last)
		#netmask has to be the same
		#go to end of prefix mask
		#only aggregate routes going to same output port
		#

		return False

	def update(self, srcif, packet):
		"""	handle update packets	"""

		# Save update message for later
		self.updates[packet["src"]] = packet

		# Add an entry to the forwarding table
		# TODO: Add functionality to prevent duplicate entries
		self.fwd_table.append({"network": packet["msg"]["network"],
							   "netmask": packet["msg"]["netmask"],
							   "localpref": packet["msg"]["localpref"],
							   "selfOrigin": packet["msg"]["selfOrigin"],
							   "ASPath": packet["msg"]["ASPath"],
							   "origin": packet["msg"]["origin"],
							   "peer": packet["src"]})

		logging.debug("Got update from {}".format(srcif))


		# Update all neighbors if srcif is CUST
		# Update received from a customer: send updates to all other neighbors
		if self.relations[srcif] == CUST:
			for sock in self.sockets:
				# Prevent self-sending
				if sock != packet["src"]:
					packet_copy = copy.deepcopy(packet)

					# Update is received at the router and passed to other sockets
					# so old dst becomes new src and sock becomes new dst
					packet_copy["src"], packet_copy["dst"] = packet_copy["dst"], sock

					self.forward(sock, packet_copy)
		else:
			for sock in self.sockets:

				# Prevent self-sending
				if sock != packet["src"] and self.relations[sock] == CUST:
					packet_copy = copy.deepcopy(packet)

					# Update is received at the router and passed to other sockets
					# so old dst becomes new src and sock becomes new dst
					packet_copy["src"], packet_copy["dst"] = packet_copy["dst"], sock

					self.forward(sock, packet_copy)
		return

	def revoke(self, packet):
		"""	handle revoke packets	"""
		rev_msg = packet["msg"]  # packet message contents

		temp = []
		for unreachable in rev_msg:
			for entry in self.fwd_table:
				if entry["network"] == unreachable["network"] and entry["netmask"] == unreachable["netmask"] and entry["peer"] == packet["src"]:
					logging.debug("{} revoked".format(unreachable["network"]))
					continue
				else:
					if entry not in temp:
						temp.append(entry)
			self.fwd_table = temp
		
		for sock in self.sockets:
			if sock != packet["src"]:
				packet_copy = copy.deepcopy(packet)

				# Update is received at the router and passed to other sockets
				# so old dst becomes new src and sock becomes new dst
				packet_copy["src"], packet_copy["dst"] = packet_copy["dst"], sock

				self.forward(sock, packet_copy)
			
			

			# TODO
		return True

	def dump(self, packet):
		"""	handles dump table requests	"""
		logging.debug(packet)

		# Forward the current forwarding table for comparison.
		# Filters socket list to exclude socket that sent the packet then takes first of list
		# self.forward([s for s in self.sockets if s != packet["src"]][0],
		self.forward(packet["src"],
					 {"src": packet["dst"],
					  "dst": packet["src"],
					  "type": "table",
					  "msg": self.fwd_table})

	def handle_packet(self, srcif, packet):
		if packet["type"] == UPDT:
			logging.warning("Handling update")
			self.update(srcif, packet)
		if packet["type"] == DATA:
			logging.warning("Checking for possible routes data message")
			self.get_route(srcif, packet)
		if packet["type"] == DUMP:
			logging.warning("Dumping forwarding table")
			self.dump(packet)
		if packet["type"] == RVKE:
			logging.warning("Revoking entry in forwarding table")
			self.revoke(packet)
		if packet["type"] == NRTE:
			logging.warning("No route for packet")
			self.send_no_route(srcif, packet)
		if packet["type"] == "wait":
			logging.warning("wait")
			pass

		return False

	def send_error(self, conn, msg):
		pass


	# returns subnet of IP based on netmask
	def get_subnet(self, ip, netmask):
		split_ip = ip.split(".")
		split_nm = netmask.split(".")
		temp = []

		# For each chunk of IP, bitwise-AND with netmask and append to temp
		for index, each in enumerate(split_ip):
			temp.append(str(int(each) & int(split_nm[index])))

		return ".".join(temp)

	def run(self):
		while True:
			socks = select.select(self.sockets.values(), [], [], 0.1)[0]
			for conn in socks:
				try:
					k = conn.recv(65535)
				except:
					# either died on a connection reset, or was SIGTERM's by parent
					return
				if k:
					for sock in self.sockets:
						if self.sockets[sock] == conn:
							srcif = sock
							msg = json.loads(k)
					if not self.handle_packet(srcif, msg):
						self.send_error(conn, msg)
				else:
					return

		return


if __name__ == "__main__":
	router = Router(args.networks)
	router.run()
