#!/usr/bin/env python


######################TODO LIST############################




#TODO Next we need to add in timers and election processes

#TODO Add in full message log with time series so that we can reconcile partitions

#TODO Optimize


import sys, socket, select, time, json, random

# Your ID number
my_id = sys.argv[1]

# The ID numbers of all the other replicas
replica_ids = sys.argv[2:]

# Connect to the network. All messages to/from other replicas and clients will
# occur over this socket
sock = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
sock.connect(my_id)

last = 0
store = {}
replica_ids.append(my_id)
messageLog = {}
rollback_temp = None
quorum_cutoff = .8
heartbeat_cutoff = .6
election_cutoff = .3
COMMIT_IDX = 0
ELECTION_RESULTS = {}

def initial_election():
    ranks = {x: int(x, 16) for x in replica_ids}
    min_id = min(ranks.values())

    for replica in ranks:
        if ranks[replica] == min_id:
            return replica

LEADER_ID = initial_election()
IS_LEADER = LEADER_ID == my_id
LEADER_ALIVE = True

is_election = False
election_time = None

REQUEST_STASH = []


class messageLogEntry():
    def __init__(self, timestamp, message):
        self.timestamp = timestamp
        self.listOfRepAcks = set()
        self.message = message
        self.acked = False

    def addRepAck(self, rep):
        self.listOfRepAcks.add(rep)

    def getListOfRepAck(self):
        return self.listOfRepAcks

    def getTimestamp(self):
        return self.timestamp

    def getMessage(self):
        return self.message

    def setToAcked(self):
        self.acked = True

    def getAcked(self):
        return self.acked

def call_election():
    global is_election, election_time

    is_election = True
    election_time = time.time()
    to_all = {"src": my_id, "dst": "FFFF", "leader": LEADER_ID, "type": "election", "by_leader": IS_LEADER}
    sock.send(json.dumps(to_all))


def send_election_bid():

    to_all = {"src": my_id, "dst": "FFFF", "leader": LEADER_ID, "type": "bid", "commitIdx": COMMIT_IDX}
    sock.send(json.dumps(to_all))


def send_heartbeat(dst):
    if dst == my_id:
        return
    to_leader = {"src": my_id, "dst": dst, "leader": LEADER_ID, "type": "heartbeat"}
    sock.send(json.dumps(to_leader))


def send_redirect(msg, leader=LEADER_ID):
    global LEADER_ID
    print("REDIRECTING")
    redirect_msg = {"src": msg['dst'], "dst": LEADER_ID, "leader": LEADER_ID, "type": "leader_redirect", "MID": msg['MID'], "target": msg["src"]}

    # redirect_msg = {"src": msg['dst'], "dst": msg["src"], "leader": leader, "type": "redirect", "MID": msg['MID']}
    sock.send(json.dumps(redirect_msg))



def leader_send_redirect(msg):
    if msg["type"] == "leader_redirect":
        redirect_msg = {"src": msg['dst'], "dst": msg["target"], "leader": my_id, "type": "redirect", "MID": msg['MID']}
    else:
        redirect_msg = {"src": msg['dst'], "dst": msg["src"], "leader": my_id, "type": "redirect", "MID": msg['MID']}

    sock.send(json.dumps(redirect_msg))


def answer_get(msg):
    if msg['key'] in store:
        return_msg = {"src": LEADER_ID,
                      "dst": msg['src'],
                      "leader": msg['leader'],
                      "type": "ok",
                      "MID": msg['MID'],
                      "value": store[msg['key']]}
    else:
        return_msg = {"src": msg['dst'],
                      "dst": msg['src'],
                      "leader": msg['leader'],
                      "type": "fail",
                      "MID": msg['MID'],
                      "value": ""}
    sock.send(json.dumps(return_msg))


def answer_put(msg):
    global COMMIT_IDX, rollback_temp, heartbeat

    # if leader, broadcast to followers
    if msg["dst"] == LEADER_ID:
        messageLog[msg["MID"]] = messageLogEntry(time.time(), msg)
        to_followers = {"src": LEADER_ID, 'dst': "FFFF", "leader": LEADER_ID, "type": "put", "MID": msg['MID'], "origin": msg["src"], 'key': msg['key'], 'value': msg['value']}
        sock.send(json.dumps(to_followers))

    # replica answer put
    elif msg["src"] == LEADER_ID:
        # store
        if msg["key"] in store:
            rollback_temp = store[msg["key"]]

        COMMIT_IDX += 1
        store[msg["key"]] = msg['value']
        # If a put is received from the leader, send an ACK back to the leader
        to_leader = {"src": my_id, 'dst': LEADER_ID, "leader": LEADER_ID, "type": "ok", "MID": msg['MID'], "origin": msg["origin"], 'key': msg['key'], 'value': msg['value']}
        sock.send(json.dumps(to_leader))

    elif msg["src"] == msg["leader"] and msg["leader"] != LEADER_ID:
        call_election()
        msg["origin"] = msg["src"]
        REQUEST_STASH.append(msg)
        # to_client = {"src": LEADER_ID, "dst": msg["src"], "leader": LEADER_ID, "type": "fail", "MID": msg['MID']}
        # sock.send(json.dumps(to_client))
        print("HERE")
        print(msg)




def quorum_timeout(start_time):
    print(time.time() - start_time)
    return time.time() - start_time > quorum_cutoff


def quorum(mid):
    return len(mid) >= len(replica_ids) // 2


def send_rollback(msg):

    if quorum(messageLog[msg["MID"]].getListOfRepAck()):
        quorum_reached(msg)

    else:
        for src in messageLog[msg["MID"]].getListOfRepAck():
            rollback_msg = {"src": LEADER_ID, "dst": src, "leader": LEADER_ID, "type": "rollback", "MID": msg['MID'], "key": msg['key']}
            sock.send(json.dumps(rollback_msg))

        to_client = {"src": LEADER_ID, "dst": msg["src"], "leader": LEADER_ID, "type": "fail", "MID": msg['MID']}
        sock.send(json.dumps(to_client))

    messageLog.pop(msg["MID"])


def answer_rollback(msg):
    global COMMIT_IDX

    COMMIT_IDX -= 1
    print("rolling back")
    if rollback_temp is not None:
        store[msg["key"]] = rollback_temp
    else:
        store.pop(msg["key"])

def quorum_reached(msg):
    global COMMIT_IDX

    to_client = {"src": LEADER_ID, 'dst': msg["origin"], "leader": LEADER_ID, "type": "ok", "MID": msg['MID']}
    sock.send(json.dumps(to_client))
    # messageLog.pop(msg["MID"])
    # This needs to be changed we should only commit to the store when we know all replicas have the change
    # We need to have this become a distributed commit
    # commit_to_store(msg)
    # Can rollback via next line
    COMMIT_IDX += 1
    store[msg["key"]] = msg['value']


def receive_acks(msg):
    if msg["MID"] in messageLog.keys():
        messageLog[msg["MID"]].addRepAck(msg["src"])
        if quorum(messageLog[msg['MID']].getListOfRepAck()):
            quorum_reached(msg)


def handle_msg_to_leader(msg):
    if msg['type'] == 'get':
        answer_get(msg)

    elif msg["type"] == 'put':
        answer_put(msg)

    elif msg["type"] == "ok":
        receive_acks(msg)

    elif msg["type"] == "heartbeat":
        send_heartbeat(msg["src"])

    elif msg["type"] == "leader_redirect":
        leader_send_redirect(msg)


def handle_msg_from_leader(msg):
    global LEADER_ALIVE, heartbeat, is_election

    if msg["type"] == 'put':
        answer_put(msg)
        #print("{} answered a put from {}".format(my_id, LEADER_ID))

    elif msg["type"] == 'rollback':
        answer_rollback(msg)
        #print("{} answered a rollback from {}".format(my_id, LEADER_ID))

    elif msg["type"] == "heartbeat":
        #print("{} answered a rollback from {}".format(my_id, LEADER_ID))
        LEADER_ALIVE = True
        is_election = False

    heartbeat = time.time()


def handle_msg_from_rep(msg):
    global LEADER_ID, is_election, election_time, heartbeat, LEADER_ALIVE, ELECTION_RESULTS, COMMIT_IDX

    if msg["type"] == "election":
        if is_election:
            heartbeat = None
            return
        if msg["by_leader"]:
            if IS_LEADER:
                send_election_bid()
                is_election = True
                election_time = time.time()
        else:
            # LEADER_ID = ""
            send_election_bid()
            is_election = True
            election_time = time.time()

    elif msg["type"] == "bid":
        ELECTION_RESULTS[msg["src"]] = msg["commitIdx"]
        ELECTION_RESULTS[my_id] = COMMIT_IDX

    elif msg["type"] == "kill":
        # Full reset
        print("{} got kill from {}".format(my_id, msg["src"]))
        LEADER_ID = msg["leader"]
        is_election = False
        LEADER_ALIVE = True
        election_time = None

    heartbeat = None


def handle_bid_or_kill_from_rep(msg):
    global LEADER_ID, is_election, election_time, LEADER_ALIVE, heartbeat, ELECTION_RESULTS, COMMIT_IDX

    if msg["type"] == "bid":
        ELECTION_RESULTS[msg["src"]] = msg["commitIdx"]
        ELECTION_RESULTS[my_id] = COMMIT_IDX

    elif msg["type"] == "kill":
        # Full reset
        print("{} got kill from {}".format(my_id, msg["src"]))

        LEADER_ID = msg["leader"]
        send_kill = {"src": my_id, 'dst': "FFFF", "leader": LEADER_ID, "type": "kill"}
        sock.send(json.dumps(send_kill))
        is_election = False
        LEADER_ALIVE = True
        election_time = None

    heartbeat = None


def check_messageLog():
    for v in messageLog.values():
        if not v.getAcked():
            if time.time() - v.getTimestamp() >= quorum_cutoff:
                send_rollback(v.getMessage())


def determine_election_result():
    global LEADER_ALIVE, is_election, LEADER_ID, election_time

    winners = {int(x, 16): x for x in ELECTION_RESULTS if ELECTION_RESULTS[x] == max(ELECTION_RESULTS.values())}
    if len(winners) > 0:
        LEADER_ID = winners[max(winners.keys())]

        if LEADER_ID == my_id:
            LEADER_ID = my_id
            send_kill = {"src": my_id, 'dst': "FFFF", "leader": my_id, "type": "kill"}
            #print(send_kill)
            sock.send(json.dumps(send_kill))

        is_election = False
        LEADER_ALIVE = True
        election_time = None


def handle_stash():
    global REQUEST_STASH, messageLog


    print("HANDLING STASH")
    for request in REQUEST_STASH:
        print(request)
        if request["dst"] == LEADER_ID:
            handle_msg_to_leader(request)
            if quorum(messageLog(request["MID"]).getListOfRepAck()):
                messageLog[request["MID"]].setToAcked()
                REQUEST_STASH.pop(request["MID"])

        #if request["leader"] != LEADER_ID:
            leader_send_redirect(request)




heartbeat = None

#####################################################
#                   Main Function                   #
#####################################################


while True:
    IS_LEADER = LEADER_ID == my_id

    ready = select.select([sock], [], [], 0.1)[0]

    # print("{}: {}".format(my_id, is_election))
    if sock in ready:
        msg_raw = sock.recv(32768)

        if len(msg_raw) == 0: continue
        msg = json.loads(msg_raw)
        # print(msg)

        if IS_LEADER:
            if not is_election:
                handle_msg_to_leader(msg)
                check_messageLog()
                if len(REQUEST_STASH) > 0:

                    handle_stash()

            else:
                LEADER_ID = "FFFF"
                send_election_bid()
                is_election = True
                election_time = time.time()


        # IS DEFINITELY REPLICA
        else:
            if not is_election:
                election_time = None
                if msg["src"] in replica_ids and msg["src"] != LEADER_ID:
                    handle_msg_from_rep(msg)

                # Must be from leader
                elif msg["src"] == LEADER_ID:
                    handle_msg_from_leader(msg)

                elif heartbeat and time.time() - heartbeat >= heartbeat_cutoff:
                    if LEADER_ALIVE:
                        send_heartbeat(LEADER_ID)
                        LEADER_ALIVE = False
                        heartbeat = time.time()

                    else:
                        print("THIS IS A HEARTBEAT TIMEOUT for {}".format(my_id))
                        is_election = True
                        call_election()
                        send_election_bid()
                        heartbeat = None

                elif msg["src"] not in replica_ids:
                    send_redirect(msg)

                else:
                    print(msg)

            else:
                heartbeat = None
                if msg["src"] in replica_ids: #and msg["src"] != LEADER_ID:
                    handle_bid_or_kill_from_rep(msg)
                    # TODO: add function to confirm kill auth

                if election_time and time.time() - election_time >= election_cutoff:
                    determine_election_result()
                    heartbeat = None


                elif msg["src"] not in replica_ids:
                    msg["origin"] = msg["src"]
                    REQUEST_STASH.append(msg)

                else:
                    pass






